build:
    environment:
        python: 3.6.0
    dependencies:
        before:
            - pip install -r requirements.txt
            - pip install -r requirements-dev.txt
    tests:
        override:
            - make lint
            - make test
