matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: "3.6"
    - os: linux
      dist: xenial
      sudo: required
      language: python
      python: "3.7"

cache:
  pip: true

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - make lint
  - make test
